<?php
/**
* Copyright © 2019 Roma Technology Limited. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<?php
$mergedCells = $this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1;
$loggedIn = $this->helper(RTech\Quote\Helper\LoggedIn::class)->isLoggedIn();
?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":{"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>","updateCartActionContainer": "#update_cart_action_container"}}'
          class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()) :?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <table id="shopping-cart-table"
               class="cart items data table"
               data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
            <caption class="table-caption"><?= $block->escapeHtml(__('Shopping Cart Items')) ?></caption>
            <thead>
                <tr>
                    <th class="col item" scope="col"><span><?= $block->escapeHtml(__('Item')) ?></span></th>
                    <th class="col price" scope="col"><span><?= $block->escapeHtml(__('Price')) ?></span></th>
                    <th class="col qty" scope="col"><span><?= $block->escapeHtml(__('Qty')) ?></span></th>
                    <th class="col subtotal" scope="col"><span><?= $block->escapeHtml(__('Subtotal')) ?></span></th>
                </tr>
            </thead>
            <?php foreach ($block->getItems() as $_item) :?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </table>
        <?php if ($block->getPagerHtml()) :?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()) :?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
      <button type="submit"
              name="update_cart_action"
              data-cart-item-update=""
              value="update_qty"
              title="<?= $block->escapeHtml(__('Update Cart')) ?>"
              class="action update"
              id="update_cart_button">
        <span><?= $block->escapeHtml(__('Update Cart')) ?></span>
      </button>
        <?php if ($loggedIn) :?>
          <button type="button"
                  name="save_cart_action"
                  data-cart-save=""
                  value="save_cart"
                  title="<?= $block->escapeHtml(__('Save')) ?>"
                  class="action clear"
                  id="save_cart_button"
                  disabled >
              <span><?= $block->escapeHtml(__('Save')) ?></span>
          </button>
        <?php endif; ?>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>


<script>
require([
  'jquery',
  'Magento_Ui/js/modal/confirm',
  'Magento_Customer/js/customer-data',
  'domReady!'
], function($, confirmation, customerData) {
  $('#save_cart_button').prop('disabled', false);

  $('#save_cart_button').click(function() {
    $('#save_cart_button').prop('disabled', true);
    var cartData = customerData.get('cart-data')();
    if (!cartData.shippingMethodCode) {
      customerData.set('messages', {
        messages: [{
          type: 'error',
          text: $.mage.__('Please select a shipping method')
        }]
      });
      clearMessage();
    } else {
      confirmation({
        title: $.mage.__('Save Quote'),
        content: $.mage.__('Do you want to save Quote?'),
        actions: {
          confirm: function() {
            $.ajax({
              showLoader: true,
              url: "<?= $block->getBaseUrl() ?>quote/quote/save/",
              type: "POST",
              data: cartData.totals,
              dataType: 'json'
            }).done(function (result) {
              if (result.status == 'ok') {
                window.location.href = "<?= $block->getBaseUrl() ?>quote/quote/success/id/" + result.id;
              }
              clearMessage();
              return true;
            });
          },
          cancel: function(){
            $('#save_cart_button').prop('disabled', false);
          }
        }
      });
    }

    function clearMessage() {
      setTimeout(function() {
        customerData.set('messages', {
          messages: []
        });
      }, 4000);
    }
  });
});
</script>
