<?php
/**
* Copyright © 2019 Roma Technology Limited. All rights reserved.
* See COPYING.txt for license details.
*/
?>
<?php $_quotes = $block->getQuotes(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_quotes && count($_quotes)) : ?>
<div class="table-wrapper models-history">
  <table class="data table table-model-items history" id="my-models-table">
    <caption class="table-caption"><?= $block->escapeHtml(__('Energy Models')) ?></caption>
    <thead>
        <tr>
          <th scope="col" class="col number"><?= $block->escapeHtml(__('Quote #')) ?></th>
          <th scope="col" class="col date"><?= $block->escapeHtml(__('Saved at')) ?></th>
          <th scope="col" class="col item_count"><?= $block->escapeHtml(__('Line Items')) ?></th>
          <th scope="col" class="col value"><?= $block->escapeHtml(__('Subtotal')) ?></th>
          <th scope="col" class="col value"><?= $block->escapeHtml(__('Shipping')) ?></th>
          <th scope="col" class="col value"><?= $block->escapeHtml(__('Tax')) ?></th>
          <th scope="col" class="col value"><?= $block->escapeHtml(__('Total')) ?></th>
          <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
        </tr>
    </thead>
    <tbody>
      <?php foreach ($_quotes as $index => $_quote) : ?>
      <tr id="<?= $_quote->getId() ?>" class="quote">
        <td data-th="<?= $block->escapeHtml(__('Quote #')) ?>" class="col number"><?= $block->escapeHtml($_quote->getId()) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Saved at')) ?>" class="col date"><?= /* @noEscape */ $block->quoteDate($_quote) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Line Items')) ?>" class="col number"><?= $block->escapeHtml($_quote->getLineitems()) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Subtotal')) ?>" class="col subtotal"><?= /* @noEscape */ $block->quoteSubtotal($_quote) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Shipping')) ?>" class="col shipping"><?= /* @noEscape */ $block->quoteShipping($_quote) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Tax')) ?>" class="col tax"><?= /* @noEscape */ $block->quoteTax($_quote) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Total')) ?>" class="col total"><?= /* @noEscape */ $block->quoteTotal($_quote) ?></td>
        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
          <a data-id="<?= $_quote->getId() ?>" href="#" class="action view-quote">
            <span><?= $block->escapeHtml(__('View')) ?></span>
          </a>
          <a data-id="<?= $_quote->getId() ?>" href="#" class="action delete-quote">
            <span><?= $block->escapeHtml(__('Delete')) ?></span>
          </a>
        </td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>
<?php if ($block->getPagerHtml()) : ?>
<div class="quotes-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
<?php endif ?>
<?php else : ?>
<div class="message info empty"><span><?= $block->escapeHtml(__('You have created no quotes.')) ?></span></div>
<?php endif ?>

<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
], function($, confirmation) {

  $('a.delete-quote').click(function() {
    okDelete($(this).attr("data-id"));
  });

  $('a.view-quote').click(function() {
    var id = $(this).attr("data-id");
    window.location.href = "<?= $block->escapeUrl($block->getViewUrl()) ?>" + 'id/' + id + '/';
  });

  function okDelete(id) {
    confirmation({
      title: $.mage.__('Confirm Deletion'),
      content: $.mage.__('Do you want to delete Quote #') + id + ' ?',
      actions: {
        confirm: function() {
          $.ajax({
            showLoader: true,
            url: "<?= $block->getDeletetUrl() ?>",
            type: "POST",
            data: {'quote_id': id},
          }).done(function (result) {
            if (result.status == 'ok') {
              location.reload();
            } else {
              deleteError(result.status);
            }
            return true;
          });
        },
        cancel: function(){}
      }
    });
  }

  function deleteError(msg) {
    confirmation({
      title: $.mage.__('Error'),
      content: $.mage.__('Unable to delete quote due to error: ') + '</br>' + msg,
      buttons: [{
        text: $.mage.__('OK'),
        class: 'action-primary action-accept',
        click: function (event) {
          this.closeModal(event, true);
        }
      }],
      actions: {
        confirm: function() {}
      }
    });
  }
});
</script>