<?php
/**
 * Copyright © 2019 Roma Technology Limited. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$_quotes = $block->getQuotes()->getItems();
$count = count($_quotes);
?>
<?php if ($count > 0) : ?>
<div class="block block-dashboard-quotes">
  <div class="block-title quotes">
    <strong><?= $block->escapeHtml(__('Recent Quotes')) ?></strong>
    <a class="action view" href="<?= $block->escapeUrl($block->getUrl('quote/quote/history')) ?>">
      <span><?= $block->escapeHtml(__('View All')) ?></span>
    </a>
    <?php endif; ?>
  </div>
  <div class="block-content">
    <?= $block->getChildHtml() ?>
    <?php if ($count > 0) : ?>
    <div class="table-wrapper quotes-recent">
      <table class="data table table-quote-items recent" id="my-quotes-table">
        <caption class="table-caption"><?= $block->escapeHtml(__('Recent Quotes')) ?></caption>
        <thead>
          <tr>
            <th scope="col" class="col number"><?= $block->escapeHtml(__('Quote #')) ?></th>
            <th scope="col" class="col date"><?= $block->escapeHtml(__('Saved at')) ?></th>
            <th scope="col" class="col item_count"><?= $block->escapeHtml(__('Line Items')) ?></th>
            <th scope="col" class="col value"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            <th scope="col" class="col value"><?= $block->escapeHtml(__('Shipping')) ?></th>
            <th scope="col" class="col value"><?= $block->escapeHtml(__('Tax')) ?></th>
            <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($_quotes as $index => $_quote) : ?>
          <tr id="<?= $_quote->getId() ?>" class="recent-quote">
            <td data-th="<?= $block->escapeHtml(__('Quote #')) ?>" class="col number"><?= $block->escapeHtml($_quote->getId()) ?></td>
            <td data-th="<?= $block->escapeHtml(__('Saved at')) ?>" class="col date"><?= /* @noEscape */ $block->quoteDate($_quote) ?></td>
            <td data-th="<?= $block->escapeHtml(__('Line Items')) ?>" class="col number"><?= $block->escapeHtml($_quote->getLineItems()) ?></td>
            <td data-th="<?= $block->escapeHtml(__('Subtotal')) ?>" class="col subtotal"><?= /* @noEscape */ $block->quoteSubtotal($_quote) ?></td>
            <td data-th="<?= $block->escapeHtml(__('Shipping')) ?>" class="col shipping"><?= /* @noEscape */ $block->quoteShipping($_quote) ?></td>
            <td data-th="<?= $block->escapeHtml(__('Tax')) ?>" class="col tax"><?= /* @noEscape */ $block->quoteTax($_quote) ?></td>
            <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
              <a data-id="<?= $_quote->getId() ?>" href="#" class="action view-quote">
                <span><?= $block->escapeHtml(__('View')) ?></span>
              </a>
              <a data-id="<?= $_quote->getId() ?>" href="#" class="action delete-quote">
                <span><?= $block->escapeHtml(__('Delete')) ?></span>
              </a>
            </td>
          </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
require([
    'jquery',
    'Magento_Ui/js/modal/confirm'
], function($, confirmation) {

  $('a.view-quote').click(function() {
    var id = $(this).attr("data-id");
    var currentCount = <?= $block->currentCartItems() ?>;
    var currentId = <?= $block->currentCartId() ?>;
    if (currentCount == 0 || currentId == id) {
      goToCart(id);
    } else {
      okToChangeCart(id);
    }
  });

  $('a.delete-quote').click(function() {
    okDelete($(this).attr("data-id"));
  });

  function okToChangeCart(id) {
    confirmation({
      title: $.mage.__('Confirm Cart Change'),
      content: $.mage.__('Do you want to replace existing cart with Quote #') + id + ' ?',
      actions: {
        confirm: function() {
          goToCart(id);
        },
        cancel: function(){}
      }
    });
  }

  function goToCart(id) {
    window.location.href = "<?= $block->escapeUrl($block->getViewUrl()) ?>" + 'id/' + id + '/';
  }

  function okDelete(id) {
    confirmation({
      title: $.mage.__('Confirm Deletion'),
      content: $.mage.__('Do you want to delete Quote ') + id + ' ?',
      actions: {
        confirm: function() {
          $.ajax({
            showLoader: true,
            url: "<?= $block->getDeletetUrl() ?>",
            type: "POST",
            data: {'quote_id': id},
          }).done(function (result) {
            if (result.status == 'ok') {
              location.reload();
            } else {
              deleteError(result.status);
            }
            return true;
          });
        },
        cancel: function(){}
      }
    });
  }

  function deleteError(msg) {
    confirmation({
      title: $.mage.__('Error'),
      content: $.mage.__('Unable to delete quote due to error: ') + '</br>' + msg,
      buttons: [{
        text: $.mage.__('OK'),
        class: 'action-primary action-accept',
        click: function (event) {
          this.closeModal(event, true);
        }
      }],
      actions: {
        confirm: function() {}
      }
    });
  }
});
</script>

<?php endif; ?>